; This template contains default settings for all transports. 
[transport-defaults](!)
type = transport
bind = 0.0.0.0

; For communication to any addresses within local_nets, Asterisk will not apply
; NAT-related workarounds.
local_net = 127.0.0.0/8
local_net = 10.0.0.0/8
local_net = 172.16.0.0/12
local_net = 192.168.0.0/16

; If you have a public static IP for your Asterisk server, set it here.
external_media_address     = 203.0.113.8
external_signaling_address = 203.0.113.8


; The following UDP and TCP transports will inherit from the defaults.
[transport-udp](transport-defaults)
protocol = udp

[transport-tcp](transport-defaults)
protocol = tcp

; ======== 3 local extensions ========

; --- 6001 ---
[6001]
type=endpoint
context=internal
disallow=all
allow=ulaw
auth=auth6001
aors=6001
; NAT-friendly defaults for phones behind NAT / Docker
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
direct_media=no

[auth6001]
type=auth
auth_type=userpass
username=6001
password=6001        ; change me

[6001]
type=aor
max_contacts=1


; --- 6002 ---
[6002]
type=endpoint
context=internal
disallow=all
allow=ulaw
auth=auth6002
aors=6002
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
direct_media=no

[auth6002]
type=auth
auth_type=userpass
username=6002
password=6002        ; change me

[6002]
type=aor
max_contacts=1


; --- 6003 ---
[6003]
type=endpoint
context=internal
disallow=all
allow=ulaw
auth=auth6003
aors=6003
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
direct_media=no

[auth6003]
type=auth
auth_type=userpass
username=6003
password=6003        ; change me

[6003]
type=aor
max_contacts=1